---
- hosts: all
  become: true
  tasks:
    - name: Desabilitar Selinux
      selinux:
        state: disabled

#    - name: Parar Servico Firewalld
#      systemd:
#        name: firewalld
#        state: stopped

#    - name: Add repository
#      yum_repository:
#      name: epel
#      description: EPEL YUM repo
#      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

#    - name: Instalar Biblioteca Epel
#     dnf:
#     name: epel-releasegit commit -m "first commit"
#     state: latest

#    - name: Instalar pacote Htop
#      dnf:
#      name: htop
#      state: latest

#    - name: Atualizando arquivo de hosts
#      template:
#        src=/etc/hosts
#        dest=/etc/hosts

